version: '3.8'

services:
  web:
    image: husnain844/chat_crud_project:latest
    command: daphne -b 0.0.0.0 -p 8000 chatproject.asgi:application
    volumes:
      - ./chatproject:/app  # Mount the 'chatproject' folder to '/app'
    working_dir: /app  # Set the working directory to '/app'
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      DJANGO_SECRET_KEY: supersecretkey
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_DB_NAME: chat_db

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
      - mongo_config:/data/configdb  # Persist MongoDB config data

  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persist Redis data

volumes:
  mongo_data:
  mongo_config:
  redis_data:
