apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-service
  namespace: my-chat-app
spec:
  hosts:
  - redis-headless.my-chat-app.svc.cluster.local
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: redis-headless.my-chat-app.svc.cluster.local
        port:
          number: 6379

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-destination-rule
  namespace: my-chat-app
spec:
  host: redis-headless.my-chat-app.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 1000
        connectTimeout: 10s
    outlierDetection:
      consecutiveErrors: 5
      interval: 10s
      baseEjectionTime: 30s
